const quizData = [
  { q: "Which is not a valid Background property CSS?", options: ["background-image", "background-position", "background-color", "background-iterate"], answer: 3 },
  { q: "What is not true about W3.CSS?", options: ["Modern framework", "Equality for all browsers", "Equality for all devices", "W3.CSS is not standard CSS"], answer: 3 },
  { q: "The ________ property allows to indent the first line of text in an element.", options: ["text-first", "text-indent", "first-indent", "text-first-indent"], answer: 1 },
  { q: "Identify the invalid HTML event.", options: ["unload", "load", "onmouseout", "onmouseover"], answer: 3 },
  { q: "W3.CSS does not provide the following border class:", options: ["w3-border-top", "w3-border-right", "w3-border-bottom", "w3-border-gutter"], answer: 3 },
  { q: "Identify the valid new <input> tag element in HTML 5?", options: ["email", "letter", "fax", "None of the above"], answer: 0 },
  { q: "Which tag is used to render an independent piece of content?", options: ["Blog", "Newspaper", "Article", "Record"], answer: 2 },
  { q: "Hypertext is a:", options: ["Heavy jargon", "More than 1000 words", "Contains links to other texts", "None"], answer: 2 },
  { q: "Which operator finds equality of type as well as content?", options: ["==", "===", "====", "None"], answer: 1 },
  { q: "What is not a valid statement for Angular JS?", options: ["JS framework", "Added via <script>", "Written in C", "Extends HTML attributes"], answer: 2 },
  { q: "W3.Table does not provide the following class:", options: ["w3-striped", "w3-stripe", "w3-border", "w3-bordered"], answer: 1 },
  { q: "Which converter is present in Notepad++?", options: ["ASCII to HEX", "ASCII to OCT", "HEX to ASCII", "Both (A) and (C)"], answer: 3 },
  { q: "Exponential operator in JavaScript is:", options: ["^", "%", "**", "None"], answer: 2 },
  { q: "A set of navigation links is defined using tag:", options: ["<a>", "<nav>", "<href>", "None"], answer: 1 },
  { q: "File protocol is used for:", options: ["File design", "Hard disk transfer", "Storage space", "Transfer from server to client"], answer: 3 },
  { q: "Generic inline element that applies no inherent formatting:", options: ["div", "span", "color", "width"], answer: 1 },
  { q: "Features of photo-editing software:", options: ["Air brushing", "Red-eye removal", "Cropping", "All of the above"], answer: 3 },
  { q: "Filter based on photographers adding colored filters to lens:", options: ["Image Filter", "Photo Filter", "Artistic Filter", "None"], answer: 1 },
  { q: "What is not true about the <label> tag?", options: ["Defines label for many elements", "Useful for screen-readers", "Useful for visually challenged", "All above"], answer: 0 },
  { q: "The body of the style sheet includes:", options: ["Style rules", "CSS rules", "Sheet rules", "Format rules"], answer: 0 },
  { q: "SGML stands for:", options: ["Standalone markup", "Global makeup", "Standard Generalized Markup Language", "Graphical markup"], answer: 2 },
  { q: "Rectangular Marquee tool is used for:", options: ["Floating marquee", "Creating marquee", "Selecting portion inside image", "None"], answer: 2 },
  { q: "Tool that uses search engine data to produce results:", options: ["Search Engine", "Meta Search Engine", "Mega Search Engine", "None"], answer: 1 },
  { q: "Are negative values allowed in padding property?", options: ["Yes", "No", "Cannot say", "Maybe"], answer: 1 },
  { q: "Pseudoclass activated when user moves mouse over element:", options: ["mouse over", "mouse hover", "hover", "mouse move"], answer: 2 },
  { q: "Encryption algorithm NOT present in Notepad++:", options: ["MD5", "SHA-256", "MD6", "Both A and B"], answer: 2 },
  { q: "Benefits of Photo Editing for Business:", options: ["Brand Building", "Better Sales", "Social Media Strategy", "All of the above"], answer: 3 },
  { q: "Not true about responsive tables in W3.Table:", options: ["w3-responsive class", "Horizontal scroll", "w3-table class creates responsive", "No diff on large screen"], answer: 2 },
  { q: "How are tones created in Images?", options: ["Adding grey", "Adding black", "Adding white", "None"], answer: 0 },
  { q: "True about Conflicting Styles:", options: ["Conflict occurs", "Styles cascade", "Appearance depends on combination", "Agent takes priority"], answer: 2 },
  { q: "Identify the basic lists in W3.CSS:", options: ["w3-ol", "w3-border", "w3-center", "All of the above"], answer: 0 },
  { q: "Wrong statement about Cookies:", options: ["Programs in background", "Violate privacy", "Shopping cart help", "Max 4 Kb"], answer: 0 },
  { q: "Which is true about <iframe> tag?", options: ["Inline frame", "Embed document", "None", "Both A and B"], answer: 3 },
  { q: "Not correct about Style class:", options: ["Apply to specific elements", "Apply to any element", "Preceded by underscore", "Preceded by period"], answer: 2 },
  { q: "Default font used in W3.Font:", options: ["Times New Roman", "Arial", "Verdana", "None of the above"], answer: 3 },
  { q: "Element can be accessed in JavaScript using:", options: ["getElementsByName", "getElementById", "getElementsByClassName", "All of the above"], answer: 3 },
  { q: "________ binds HTML controls value to application data:", options: ["ng-app", "ng-init", "ng-model", "ng-controller"], answer: 2 },
  { q: "Not a valid encoding standard in Notepad++:", options: ["ANSI", "UTF-8", "UTF-8 BOM", "UTF-16"], answer: 3 },
  { q: "Directive to initialize Angular JS application:", options: ["ng-app", "ng-init", "ng-model", "None"], answer: 0 },
  { q: "Browsers usually underline inserted text in which tag?", options: ["<i>", "<ins>", "<u>", "<em>"], answer: 1 },
  { q: "Identify the invalid image filter:", options: ["Motion Blur", "Plastic Wrap", "Liquify", "Solidify"], answer: 3 },
  { q: "<del> element displays text as:", options: ["Red color", "Strikethrough", "Bold", "Black color"], answer: 1 },
  { q: "w3-container class adds padding:", options: ["16px left", "32px L/R", "16px L/R", "32px right"], answer: 2 },
  { q: "Shortcut for rotating canvas 90 Degree clockwise:", options: ["CTRL+Shift+0", "CTRL+Alt+Shift+0", "CTRL+Alt+Shift+F10", "None"], answer: 1 },
  { q: "Task of DNS Name server:", options: ["Translating domain to IP", "Translate to UDP", "Translate to TCP", "Translate to FTP"], answer: 0 },
  { q: "Which is not a main built-in search mechanism?", options: ["dialog-based", "dialog-free", "Incremental Search", "Decremental Search"], answer: 3 },
  { q: "Autofocus attribute used on which element?", options: ["Button", "Input", "Select", "All the above"], answer: 1 },
  { q: "Where can a <section> element be used?", options: ["Chapters", "Introduction", "News Item", "All the above"], answer: 3 },
  { q: "How to specify individual items in an ordered list?", options: ["LI", "UL", "OI", "None"], answer: 0 },
  { q: "Which is not a valid CSS type?", options: ["Inline", "External", "Outline", "Embedded"], answer: 2 },
  { q: "Service to host website on Web Server:", options: ["Web Service", "Web Hosting", "Web Marketing", "Web Publishing"], answer: 1 },
  { q: "Which is not a vibrant color?", options: ["Red", "Orange", "White", "Purple"], answer: 2 },
  { q: "NOT a correct Image Class in W3.Image:", options: ["w3-round", "w3-circle", "w3-border", "w3-oval"], answer: 3 },
  { q: "Cluster elements together for formatting:", options: ["tag", "class", "id", "div"], answer: 1 },
  { q: "Statement for Absolute Positioning in CSS:", options: ["Browser determined", "Uses position property", "Authors get control", "None"], answer: 1 },
  { q: "Columns supported in responsive grid:", options: ["10", "11", "12", "13"], answer: 2 },
  { q: "Role of JavaScript in web design:", options: ["Content", "Layout", "Program behavior", "None"], answer: 2 },
  { q: "Not a valid meta search engine:", options: ["Yahoo", "Startpage", "Excite", "DuckDuckGo"], answer: 0 },
  { q: "Identify user actions/browser actions:", options: ["Input handler", "Event handler", "Document handler", "Action handler"], answer: 1 },
  { q: "Quick Selection tool purpose:", options: ["Copy", "Paste", "Find edges automatically", "None"], answer: 2 },
  { q: "True about CSS Box model:", options: ["Virtual box around elements", "Padding only", "Border only", "Margin only"], answer: 0 },
  { q: "Incorrect media type in CSS 2:", options: ["Handheld", "Braille", "Arial", "Print"], answer: 2 },
  { q: "w3-color classes can be used on:", options: ["Any HTML element", "Heading only", "Paragraph only", "Table only"], answer: 0 },
  { q: "Gaussian Blur shortcut key:", options: ["CTRL+Alt+Shift+G", "CTRL+Alt+G", "CTRL+Shift+G", "None"], answer: 0 },
  { q: "Not true about External Style sheet:", options: ["Separate document", "Both in single file", "Split files", "Collaboration"], answer: 1 },
  { q: "Wrong for Angular JS Expressions:", options: ["Double braces", "ng-bind", "Returns result", "Same as JS expressions"], answer: 3 },
  { q: "Tag to embed CSS in web page:", options: ["<html>", "<style>", "<css>", "<xml>"], answer: 1 },
  { q: "Not true about ng-repeat:", options: ["Repeats HTML", "Clones elements", "Array of objects", "Defines initial values"], answer: 3 },
  { q: "Operator for variable datatype in JS:", options: ["instanceof", "gettype", "typeof", "None"], answer: 2 },
  { q: "MIME stands for:", options: ["Multipurpose Internet Mail Extensions", "Instant Mail", "Internet Message", "Instant Message Exchange"], answer: 0 },
  { q: "Shortcut to hide lines in Notepad++:", options: ["Alt+H", "Shift+H", "CTRL+H", "None"], answer: 0 },
  { q: "Not a type of Screen frames:", options: ["iframe", "uframe", "no frame", "frameset"], answer: 1 },
  { q: "Lasso tool best use:", options: ["Cleaning selection", "Deselect", "Delete", "None"], answer: 0 },
  { q: "Directive to start Angular JS:", options: ["ng-repeat", "ng-init", "ng-app", "ng-model"], answer: 2 },
  { q: "Makes text bold in CSS:", options: ["font-length", "font-weight", "font-style", "text-align"], answer: 1 },
  { q: "Head element is a container for:", options: ["Links", "Webpages", "Metadata", "Pictures"], answer: 2 },
  { q: "Browser that renders HTML 5:", options: ["Safari", "Chrome", "Edge", "All the above"], answer: 3 },
  { q: "Not true for W3.Font headings:", options: ["Segoe UI default", "Narrow spacing", "Less letters allowed", "Smallest is h6"], answer: 2 },
  { q: "Not true about Embedded Style Sheets:", options: ["Embed in head", "Class selectors used", "Type is MIME", "All correct"], answer: 3 },
  { q: "True for w3-panel:", options: ["For notes", "For quotes", "For alerts", "All correct"], answer: 3 },
  { q: "Wrong for CSS PseudoClass:", options: ["Style class", "Non-explicit content", "Separated by underscore", "Separated by colon"], answer: 2 },
  { q: "Color enhancement means:", options: ["Foreground only", "Modify diamond color", "Background only", "None"], answer: 1 },
  { q: "JS keyword for older browsers:", options: ["var", "let", "const", "None"], answer: 0 },
  { q: "First CSS W3C Recommendation:", options: ["CSS 2", "CSS 0", "CSS 1", "CSS 2.1"], answer: 2 },
  { q: "JS variables cannot be declared by:", options: ["var", "let", "nothing", "set"], answer: 3 },
  { q: "Property for image transparency:", options: ["w3-opacity", "w3-trans", "w3-grayscale", "None"], answer: 0 },
  { q: "Index page is:", options: ["Encyclopedia", "Internet storage", "Access necessity", "First page of website"], answer: 3 },
  { q: "HTTP PUT method is used to:", options: ["Return contents", "Return header", "Replace document", "Execute document"], answer: 2 },
  { q: "Statement to exit switch block?", options: ["exit", "break", "default", "out"], answer: 1 },
  { q: "CSS syntax for ID 'demo'?", options: ["#demo", ".demo", "demo", "*demo"], answer: 0 },
  { q: "Largest heading tag:", options: ["<heading>", "<h6>", "<h1>", "<head>"], answer: 2 },
  { q: "W3.CSS class for circular image:", options: ["w3-round", "w3-circle", "w3-oval", "w3-img-circle"], answer: 1 },
  { q: "JS result '10' + 5:", options: ["15", "105", "Error", "NaN"], answer: 1 },
  { q: "Change text color property:", options: ["font-color", "text-color", "color", "background-color"], answer: 2 },
  { q: "Notepad++ is a:", options: ["Browser", "Text Editor", "Compiler", "OS"], answer: 1 },
  { q: "HTML line break tag:", options: ["<lb>", "<break>", "<br>", "<hr>"], answer: 2 },
  { q: "W3.CSS container class:", options: ["w3-box", "w3-container", "w3-panel", "w3-section"], answer: 1 },
  { q: "Control text size property:", options: ["font-style", "text-size", "font-size", "text-style"], answer: 2 },
  { q: "JavaScript side language:", options: ["Server", "Client", "Both", "None"], answer: 1 },
  { q: "Protocol for sending email:", options: ["HTTP", "FTP", "SMTP", "SSH"], answer: 2 }
];
